### ISSUE TITLE
python多线程

### ISSUE THREAD

**Issue by bloodzer0** [sowish/LNScan#1]
python多线程其实还是单线程，想问问你是怎么处理的呢？

**Comment by sowish** [comment]
python多线程还是有意义的，主要是用在IO密集型，比如进行敏感文件扫描，需要考虑到网络延时，所以这里使用多线程可以节省时间。这里我对每个ip使用的多进程(mutiprocessing)的方式扫描端口和tiitle

**Comment by bloodzer0** [comment]
我在进行利用的时候发现，使用多线程效果并不好，可能会造成误报！相对而言并发会好一些！

**Comment by sowish** [comment]
多线程在调度上还是有些优势的，可以更大限度合理的利用时间；你说的并发应该是多进程吧

**Comment by bloodzer0** [comment]
了解了！
